const { book, addBook, bookId, deleteBook, updateBook } = require("../controller/Book")
const { route } = require("./authRoutes")
const {verifyToken}=require("../middleware/verifyToken")
const router=require("express").Router()
router.get("/book",verifyToken,book)
router.post("/addBook",addBook)
router.get("/book/:id",bookId)
router.delete("/book/:id",deleteBook)
router.put("/book/:id",updateBook)
module.exports=router